In [2]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/75/08/67cc404b3a966b6df27b38370ddd96b3b023030b572283d035181854aac5/pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/d7/7c/f5ee1bf6ed888494978046a809df2882aad35d414b622893322df7286879/numpy-2.4.3-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-2.4.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.7 MB 1.9 MB/s eta 0:00:06
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.1/9.7 MB 369.8 kB/s eta 0:00:26
    --------------------------------------- 0.2/9.7 MB 311.7 kB/s eta 0:00:31
   - -------------------------------------- 0.2/9.7 MB 358.5 kB/s eta 0:00:27
   - -------------------------------------- 0.2/9.7 MB 358.5 kB/s eta 0:00:27
   - -------------------------------------- 0.2/9.7 MB 358.5 kB/s eta 0:00:27
   - -------------------------------------- 0.2/9.7 MB 358.5 kB/s eta 0:00:27
   - -------------------------------------- 0.2/9.7 MB 358.5 kB/s eta 0:00:27
   - -------------------------------------- 0.3/9.7 MB 293.5 kB/s eta 0:00:33
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.7 MB 377.6 kB/s eta 0:00:25
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.7 MB 355.9 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.7 MB 356.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   -- ------------------------------------- 0.7/9.7 MB 349.5 kB/s eta 0:00:26
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 360.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   --- ------------------------------------ 0.9/9.7 MB 348.2 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.7 MB 349.5 kB/s eta 0:00:26
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.1/9.7 MB 349.0 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 342.6 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/9.7 MB 350.1 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.7 MB 349.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/9.7 MB 345.4 kB/s eta 0:00:25
   ------ --------------------------------- 1.5/9.7 MB 334.7 kB/s eta 0:00:25
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.5/9.7 MB 347.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.7 MB 350.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.7/9.7 MB 301.9 kB/s eta 0:00:27
   ------ --------------------------------- 1.7/9.7 MB 301.9 kB/s eta 0:00:27
   ------ --------------------------------- 1.7/9.7 MB 301.9 kB/s eta 0:00:27
   ------ --------------------------------- 1.7/9.7 MB 301.9 kB/s eta 0:00:27
   ------ --------------------------------- 1.7/9.7 MB 301.9 kB/s eta 0:00:27
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.7/9.7 MB 293.0 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 286.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 286.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 285.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 285.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 285.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 285.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.7 MB 285.9 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 285.7 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 286.8 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 286.8 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 286.8 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 286.8 kB/s eta 0:00:28
   ------- -------------------------------- 1.9/9.7 MB 286.8 kB/s eta 0:00:28
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.0/9.7 MB 288.3 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.7 MB 290.0 kB/s eta 0:00:27
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.2/9.7 MB 292.9 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 288.3 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.3/9.7 MB 293.0 kB/s eta 0:00:26
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   --------- ------------------------------ 2.4/9.7 MB 297.4 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 291.3 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.5/9.7 MB 299.2 kB/s eta 0:00:25
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 301.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ---------- ----------------------------- 2.7/9.7 MB 278.9 kB/s eta 0:00:26
   ----------- ---------------------------- 2.7/9.7 MB 272.3 kB/s eta 0:00:26
   ----------- ---------------------------- 2.8/9.7 MB 280.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.8/9.7 MB 280.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.8/9.7 MB 280.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.8/9.7 MB 280.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.8/9.7 MB 280.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.8/9.7 MB 277.8 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.7 MB 280.9 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 281.3 kB/s eta 0:00:25
   ------------ --------------------------- 3.0/9.7 MB 279.2 kB/s eta 0:00:25
   ------------ --------------------------- 3.1/9.7 MB 282.6 kB/s eta 0:00:24
   ------------ --------------------------- 3.1/9.7 MB 282.6 kB/s eta 0:00:24
   ------------ --------------------------- 3.1/9.7 MB 282.6 kB/s eta 0:00:24
   ------------ --------------------------- 3.1/9.7 MB 282.6 kB/s eta 0:00:24
   ------------ --------------------------- 3.1/9.7 MB 282.6 kB/s eta 0:00:24

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv("superstore.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [9]:
# Summary statistics using .describe()
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,...,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,NaN,5009,1237,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,5/9/2016,16/12/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5968,37,37,5191,9994,915,...,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
std,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,2.225110,0.206452,234.260108
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [10]:
#check for duplicates
duplicate_count = df.duplicated().sum()
print("duplicates : ", duplicate_count)

duplicates :  0

In [11]:
#check for null (missing) values
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
#trim string columns for unwanted spaces
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [13]:
# Renaming columns according to snake casing for better readability and documentation
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns = df.columns.str.replace('-','_')
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [14]:
# Drop Row ID (Redundant for SQL)
df = df.drop(columns=['row_id'])
df

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [15]:
!pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Obtaining dependency information for sqlalchemy from https://files.pythonhosted.org/packages/f2/af/c3c7e1f3a2b383155a16454df62ae8c62a30dd238e42e68c24cebebbfae6/sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl.metadata
  Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Obtaining dependency information for psycopg2-binary from https://files.pythonhosted.org/packages/b1/d2/99b55e85832ccde77b211738ff3925a5d73ad183c0b37bcbbe5a8ff04978/psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata
  Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Obtaining dependency information for greenlet>=1 from https://files.pythonhosted.org/packages/9b/40/cc802e067d02af8b60b6771cea7d57e21ef5e6659912814babb42b864713/greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata
  Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
    --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
    --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
    --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
    --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
    --------------------------------------- 0.0/2.1 MB 115.9 kB/s eta 0:00:19
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   --- ------------------------------------ 0.2/2.1 MB 256.0 kB/s eta 0:00:08
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.2/2.1 MB 237.3 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/2.1 MB 218.6 kB/s eta 0:00:09
   ------ --------------------------------- 0.3/2.1 MB 225.5 kB/s eta 0:00:09
   ------ --------------------------------- 0.3/2.1 MB 225.5 kB/s eta 0:00:09
   ------ --------------------------------- 0.3/2.1 MB 225.5 kB/s eta 0:00:09
   ------ --------------------------------- 0.3/2.1 MB 225.5 kB/s eta 0:00:09
   ------ --------------------------------- 0.3/2.1 MB 225.5 kB/s eta 0:00:09
   ------ --------------------------------- 0.4/2.1 MB 208.6 kB/s eta 0:00:09
   ------- -------------------------------- 0.4/2.1 MB 220.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.1 MB 220.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.1 MB 220.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.1 MB 220.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.1 MB 220.5 kB/s eta 0:00:08
   -------- ------------------------------- 0.4/2.1 MB 209.9 kB/s eta 0:00:09
   -------- ------------------------------- 0.5/2.1 MB 230.4 kB/s eta 0:00:08
   -------- ------------------------------- 0.5/2.1 MB 230.4 kB/s eta 0:00:08
   -------- ------------------------------- 0.5/2.1 MB 230.4 kB/s eta 0:00:08
   -------- ------------------------------- 0.5/2.1 MB 230.4 kB/s eta 0:00:08
   -------- ------------------------------- 0.5/2.1 MB 230.4 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.1 MB 229.0 kB/s eta 0:00:08
   ----------- ---------------------------- 0.6/2.1 MB 229.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.6/2.1 MB 229.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.6/2.1 MB 229.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.6/2.1 MB 229.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.6/2.1 MB 229.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.6/2.1 MB 224.6 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.1 MB 236.7 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.1 MB 236.7 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.1 MB 236.7 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.1 MB 236.7 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.1 MB 236.7 kB/s eta 0:00:07
   ------------- -------------------------- 0.7/2.1 MB 226.2 kB/s eta 0:00:07
   ------------- -------------------------- 0.7/2.1 MB 239.5 kB/s eta 0:00:06
   ------------- -------------------------- 0.7/2.1 MB 239.5 kB/s eta 0:00:06
   ------------- -------------------------- 0.7/2.1 MB 239.5 kB/s eta 0:00:06
   ------------- -------------------------- 0.7/2.1 MB 239.5 kB/s eta 0:00:06
   -------------- ------------------------- 0.8/2.1 MB 226.8 kB/s eta 0:00:07
   -------------- ------------------------- 0.8/2.1 MB 235.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.1 MB 243.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.1 MB 243.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.1 MB 243.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.1 MB 243.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.1 MB 231.8 kB/s eta 0:00:06
   ---------------- ----------------------- 0.9/2.1 MB 242.9 kB/s eta 0:00:06
   ---------------- ----------------------- 0.9/2.1 MB 242.9 kB/s eta 0:00:06
   ---------------- ----------------------- 0.9/2.1 MB 242.9 kB/s eta 0:00:06
   ---------------- ----------------------- 0.9/2.1 MB 242.9 kB/s eta 0:00:06
   ---------------- ----------------------- 0.9/2.1 MB 242.9 kB/s eta 0:00:06
   ----------------- ---------------------- 0.9/2.1 MB 236.2 kB/s eta 0:00:06
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.1 MB 247.4 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.1/2.1 MB 246.1 kB/s eta 0:00:05
   --------------------- ------------------ 1.2/2.1 MB 243.1 kB/s eta 0:00:05
   --------------------- ------------------ 1.2/2.1 MB 243.1 kB/s eta 0:00:05
   --------------------- ------------------ 1.2/2.1 MB 243.1 kB/s eta 0:00:05
   --------------------- ------------------ 1.2/2.1 MB 243.1 kB/s eta 0:00:05
   --------------------- ------------------ 1.2/2.1 MB 243.1 kB/s eta 0:00:05
   ---------------------- ----------------- 1.2/2.1 MB 236.3 kB/s eta 0:00:05
   ---------------------- ----------------- 1.2/2.1 MB 240.4 kB/s eta 0:00:04
   ---------------------- ----------------- 1.2/2.1 MB 240.4 kB/s eta 0:00:04
   ---------------------- ----------------- 1.2/2.1 MB 240.4 kB/s eta 0:00:04
   ---------------------- ----------------- 1.2/2.1 MB 240.4 kB/s eta 0:00:04
   ---------------------- ----------------- 1.2/2.1 MB 240.4 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.1 MB 239.9 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 240.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 240.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 240.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 240.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 240.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.4/2.1 MB 232.0 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 240.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 240.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 240.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 240.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 240.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.4/2.1 MB 233.7 kB/s eta 0:00:04
   --------------------------- ------------ 1.5/2.1 MB 243.2 kB/s eta 0:00:03
   --------------------------- ------------ 1.5/2.1 MB 243.2 kB/s eta 0:00:03
   --------------------------- ------------ 1.5/2.1 MB 243.2 kB/s eta 0:00:03
   --------------------------- ------------ 1.5/2.1 MB 243.2 kB/s eta 0:00:03
   --------------------------- ------------ 1.5/2.1 MB 243.2 kB/s eta 0:00:03
   ---------------------------- ----------- 1.5/2.1 MB 242.2 kB/s eta 0:00:03
   ---------------------------- ----------- 1.5/2.1 MB 242.2 kB/s eta 0:00:03
   ---------------------------- ----------- 1.5/2.1 MB 242.2 kB/s eta 0:00:03
   ---------------------------- ----------- 1.5/2.1 MB 242.2 kB/s eta 0:00:03
   ---------------------------- ----------- 1.5/2.1 MB 242.2 kB/s eta 0:00:03
   ----------------------------- ---------- 1.6/2.1 MB 237.2 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 244.8 kB/s eta 0:00:03
   ------------------------------- -------- 1.7/2.1 MB 224.9 kB/s eta 0:00:03
   -------------------------------- ------- 1.8/2.1 MB 236.4 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.1 MB 236.4 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.1 MB 236.4 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.1 MB 236.4 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.1 MB 236.4 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 231.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 234.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 234.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 234.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 234.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 234.9 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 231.4 kB/s eta 0:00:02
   ---------------------------------- ----- 1.9/2.1 MB 234.3 kB/s eta 0:00:02
   ---------------------------------- ----- 1.9/2.1 MB 234.3 kB/s eta 0:00:02
   ---------------------------------- ----- 1.9/2.1 MB 234.3 kB/s eta 0:00:02
   ---------------------------------- ----- 1.9/2.1 MB 234.3 kB/s eta 0:00:02
   ---------------------------------- ----- 1.9/2.1 MB 234.3 kB/s eta 0:00:02
   ----------------------------------- ---- 1.9/2.1 MB 233.4 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 235.5 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 235.5 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 235.5 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 235.5 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.1 MB 230.6 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 235.4 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 235.4 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 235.4 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 235.4 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 235.4 kB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 232.6 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 236.4 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 236.4 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 236.4 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 236.4 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 236.4 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 235.5 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 236.1 kB/s eta 0:00:00
Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
    --------------------------------------- 0.1/2.7 MB 74.9 kB/s eta 0:00:36
    --------------------------------------- 0.1/2.7 MB 74.9 kB/s eta 0:00:36
    --------------------------------------- 0.1/2.7 MB 74.9 kB/s eta 0:00:36
    --------------------------------------- 0.1/2.7 MB 74.9 kB/s eta 0:00:36
    --------------------------------------- 0.1/2.7 MB 68.3 kB/s eta 0:00:39
   - -------------------------------------- 0.1/2.7 MB 109.2 kB/s eta 0:00:25
   -- ------------------------------------- 0.1/2.7 MB 163.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.7 MB 163.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.7 MB 163.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.7 MB 163.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.7 MB 163.7 kB/s eta 0:00:16
   -- ------------------------------------- 0.2/2.7 MB 144.5 kB/s eta 0:00:18
   -- ------------------------------------- 0.2/2.7 MB 171.0 kB/s eta 0:00:15
   -- ------------------------------------- 0.2/2.7 MB 171.0 kB/s eta 0:00:15
   -- ------------------------------------- 0.2/2.7 MB 171.0 kB/s eta 0:00:15
   -- ------------------------------------- 0.2/2.7 MB 171.0 kB/s eta 0:00:15
   -- ------------------------------------- 0.2/2.7 MB 171.0 kB/s eta 0:00:15
   --- ------------------------------------ 0.2/2.7 MB 175.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.2/2.7 MB 175.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.2/2.7 MB 175.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.2/2.7 MB 175.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.3/2.7 MB 158.9 kB/s eta 0:00:16
   --- ------------------------------------ 0.3/2.7 MB 165.5 kB/s eta 0:00:15
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.3/2.7 MB 189.0 kB/s eta 0:00:13
   ----- ---------------------------------- 0.3/2.7 MB 180.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.7 MB 180.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.7 MB 180.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.7 MB 180.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.3/2.7 MB 180.2 kB/s eta 0:00:14

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sqlalchemy import create_engine, text
import psycopg2

In [17]:
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "root"          # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "Sales"         # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "orders"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'orders' in database 'Sales'.

In [18]:
# Select all data
data = pd.read_sql(f"SELECT * FROM {table_name}", engine)
data

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480